language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages

install:
  - yarn add elm@elm0.19.0 elm-test@beta

script:
  - yarn test
