language: node_js
node_js:
  - "lts/*"

cache:
  yarn: true
  directories:
    - node_modules
    - elm-stuff/build-artifacts
    - elm-stuff/packages

install:
  - yarn add --dev elm elm-test@beta

script:
  - yarn run elm-test
