name: Elm

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js LTS
      uses: actions/setup-node@v1
      with:
        node-version: lts
    - name: Install elm
      run: npm install elm elm-test
    - name: Run tests
      run: elm-test
